"""empty message

Revision ID: 450258db6c89
Revises: ec7c2573bd11
Create Date: 2022-10-13 16:05:38.830047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450258db6c89'
down_revision = 'ec7c2573bd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Acctype')
    op.add_column('Users', sa.Column('DOB', sa.String(length=12), nullable=False))
    op.drop_column('Users', 'DOB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('DOB', sa.VARCHAR(length=14), nullable=False))
    op.drop_column('Users', 'DOB')
    op.create_table('Acctype',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('max_withdrawal_amount', sa.INTEGER(), nullable=True),
    sa.Column('min_balance', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_by', sa.VARCHAR(), nullable=True),
    sa.Column('max_withdrawal', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['modified_by'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
