"""empty message

Revision ID: 8a15467e543a
Revises: 450258db6c89
Create Date: 2022-10-13 16:12:45.056251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a15467e543a'
down_revision = '450258db6c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('DOB', sa.String(length=12), nullable=False))
    op.drop_column('Users', 'DOB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('DOB', sa.VARCHAR(length=14), nullable=False))
    op.drop_column('Users', 'DOB')
    # ### end Alembic commands ###
