"""empty message

Revision ID: ec7c2573bd11
Revises: d3ff85440ee0
Create Date: 2022-10-10 16:27:16.013511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7c2573bd11'
down_revision = 'd3ff85440ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Acctype', sa.Column('max_withdrawal', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'Acctype', type_='foreignkey')
    op.drop_column('Acctype', 'max_withdrawal_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Acctype', sa.Column('max_withdrawal_amount', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'Acctype', 'Users', ['modified_by'], ['id'])
    op.drop_column('Acctype', 'max_withdrawal')
    # ### end Alembic commands ###
